FROM node:22-alpine

WORKDIR /usr/src/app

ENV NODE_ENV=development

# Пакеты и Prisma-схема для генерации клиента
COPY package*.json ./
COPY prisma ./prisma
COPY prisma.config.ts ./

# Устанавливаем зависимости (включая dev-зависимости) и генерим Prisma Client
RUN npm install
RUN npx prisma generate

EXPOSE 4000

CMD ["npm", "run", "start:dev"]

